#!/bin/sh
# ### git commit message template ###
git config commit.template .git/templatemessage
TICKETID=`git rev-parse --abbrev-ref HEAD | LC_ALL=en_US.utf8 grep -oP '^((copilot\/)?(feature|bug|bugfix|fix|hotfix|task|chore)\/)?\K\d{1,7}' || true`
if [ -z "$TICKETID" ]
then
  TICKETID="0"
fi
TEMPLATE="#$TICKETID: "
echo "[POST-CHECKOUT] Setting template commit to '$TEMPLATE'"
echo "$TEMPLATE" > ".git/templatemessage"

if [ "${SKIP_HOOKS:-0}" -gt 0 ] 2>/dev/null; then
  echo "[POST-CHECKOUT] skipping hooks ($SKIP_HOOKS)"
  exit 0
fi

echo "[POST-CHECKOUT] 📦 Checking for changes to dependencies"
NEWHEAD=$1
OLDHEAD=$2
PACKAGES=$(git diff --name-only "$OLDHEAD" "$NEWHEAD" | grep -E "^package-lock\.json" || true)

if [ -n "$PACKAGES" ]; then
  for package in $PACKAGES; do
    echo "📦 $package was changed."
  done
  echo "📦 Running npm install to update your dependencies..."
  npm install --no-workspaces
  npm run lint:fix
else
  echo "📦 All packages up-to-date. No need to run npm install."
fi
